## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: bionic

os:
  - linux
#  - osx

julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly

notifications:
  email: false

git:
  depth: 99999999

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
  allow_failures:
    - julia: nightly

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
